Description: >
  capstone  stack.
Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub capstone-${ID}
      GroupDescription: Allow port 22 and port 5000.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: circleCI
      ImageId: ami-09e67e426f25ce0d7 
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
          
  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Tags:
        - Key: Name
          Value: !Sub EIP-${ID}
  MyEIPAssoc:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt MyEIP.AllocationId
      InstanceId: !Ref EC2Instance
Outputs:
  EIPAddress:
    Value: !Ref MyEIP
    Description: URL for ELASTIC attached to EC2
    Export:
      Name: !Sub EIP-${ID}